@startuml Forgot Password (POST)
title "Forgot Password (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as authRouter
participant "<<controller>>\n:auth" as authController
participant "<<model>>\n:User" as userModel
database "<<MongoDB>>\n:users" as users
participant "<<controllers>>\n:mailer" as mailerController

client -> server ++:req.post('/auth/forgotpassword')
server -> authRouter ++:app.use('/auth', authRouter)
authRouter -> authController ++:forgotPassword()
authController -> userModel ++:findOne({email})
userModel -> users ++:UserSchema
users --> userModel --:user
userModel --> authController --:user

authController -> mailerController ++:sendEmail(req.user.email,newPassword)
mailerController --> authController --:response
authController --> client --:response
