@startuml
left to right direction
package "Restaurant reservator"{
    class "<<Application>>\nRestaurant reservator Service" as RestaurantReservatorService{}

    class "<<Resource>>\nRestaurants" as ResourceRestaurants{
        <<GET>> +getRestaurants():Restaurant
        <<POST>> +createRestaurant():Restaurant
    }

    class "<<Resource>>\nRestaurant" as ResourceRestaurant {
        <<GET>> +getRestaurant(): Restaurant
        <<PUT>> +updateRestaurant(): Restaurant
        <<DELETE>> +deleteRestaurant(): void
    }

    class "<<Representation>>\nRestaurant" as RepresentationRestaurant {
        -name
        -address
        -tel
        -openTime
        -closeTime
    }

    class "<<Resource>>\nReservations" as ResourceReservations{
        <<GET>> +getReservations():Reservation
        <<POST>> +createReservation():Reservation
    }

    class "<<Resource>>\nReservation" as ResourceReservation {
        <<GET>> +getReservation(): Reservation
        <<PUT>> +updateReservation(): Reservation
        <<PUT>> +updateRating(): Reservation
        <<DELETE>> +deleteReservation(): void
    }

    class "<<Representation>>\nReservation" as RepresentationReservation {
        -user
        -restaurant
        -date
        -rating
    }

    class "<<Resource>>\nAuth" as ResourceAuth {
        <<POST>> +register(): User
        <<POST>> +login(): User
        <<GET>> +logout(): void
        <<GET>> +getMe(): User
        <<POST>> +forgotPassword(): void
        <<PUT>> +changePassword(): User
    }

    class "<<Representation>>\nUser" as RepresentationUser {
        -name
        -tel
        -email
        -password
    }


}

RestaurantReservatorService ..> ResourceRestaurants:"/restaurants\n<<Path>>"
ResourceRestaurants ..> ResourceRestaurant: "/{restaurantId}\n<<Path>>"
ResourceRestaurant ..> RepresentationRestaurant: "<<use>>"

RestaurantReservatorService ..> ResourceReservations:"/reservations\n<<Path>>"
ResourceReservations ..> ResourceReservation: "/{reservationId}\n<<Path>>"
ResourceReservation ..> RepresentationReservation: "<<use>>"

RestaurantReservatorService ..> ResourceAuth:"/auth\n<<Path>>"
ResourceAuth ..> RepresentationUser: "<<use>>"


@enduml